version: '3.8'
services:
  hunter-bot:
    build: .
    container_name: janek_hunter
    restart: always
    volumes:
      # Mapujemy cały bieżący folder (.) do folderu /app w kontenerze
      - .:/app
      # Zapobiega nadpisaniu node_modules/venv wewnątrz kontenera
      - /app/.venv
      - /app/__pycache__
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
